name: mnist-preprocessing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3
  - pip:
      - pandas==2.0.3
      - numpy==1.24.3
      - scikit-learn==1.3.0
      - azureml-core==1.53.0
