name: mnist-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3
  - pip:
      - numpy==1.24.3
      - tensorflow==2.15.0
      - mlflow==2.8.0
      - azureml-core==1.53.0
      - azureml-mlflow==1.53.0
