$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: mnist-training
version: 1
description: Environment for MNIST model training
conda_file: conda-training.yaml
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
